### ISSUE TITLE
Weights can't be entered with coma as the decimal separator. It could before. On IOS, keyboards from europe only allow input of the comma not the dot when in the numerical keypad. Currently we cannot enter decimal points and can only increment by half a kilo, and that is only because of the 2.5 kg default.

### ISSUE THREAD

**Issue by BehrozRazaq** [LiamMorrow/LiftLog#332] opened 2024-12-01 12:05 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LiamMorrow** [comment] 2024-12-01 22:42
Thanks for the report @BehrozRazaq ! I'll have a look at what's going on

**Comment by LiamMorrow** [comment] 2024-12-03 06:10
I have been unable to reproduce on an ios simulator, when setting the language / locale to one which uses comma as a separator, the keyboard correctly shows the comma, and LiftLog correctly parses it:

https://github.com/user-attachments/assets/c12f4019-ddf1-45fe-a560-b9df17cadbab

![Screenshot 2024-12-03 at 17 09 12](https://github.com/user-attachments/assets/192d9ed4-899a-4755-b78e-88b45fd1a9e9)

**Comment by LiamMorrow** [comment] 2024-12-03 06:15
Would you be able to take a video or series of screenshots showing off the behaviour you are seeing?

**Comment by BehrozRazaq** [comment] 2024-12-03 06:54
Yeah ofc, thanks for taking the time. ![image](https://github.com/user-attachments/assets/db3db426-fa3b-44c7-8b07-87656f63f32e)

https://github.com/user-attachments/assets/a6fb4d19-8b47-453e-9d20-acedc2c1c157

**Comment by BehrozRazaq** [comment] 2024-12-03 06:55
It used to work fine, i'm currently on v.18.1.1 of ios

**Comment by LiamMorrow** [comment] 2024-12-03 07:35
Fantastic! Thanks for the video, that helps a lot!  Seems there is a bug when using English as the main language, but commas as separators.

Just to explain it a bit more technically:
* .NET has something called a CultureInfo, which determines many things to do with Globalization, including decimal separators.
* It seems that when you use English, it does not respect iOS's number format provider, instead, just always using EN-US.

I have no idea why it used to work for you, but I'll see if I can explicitly get the number format and use that, rather than the CultureInfo format

**Comment by LiamMorrow** [comment] 2024-12-03 07:58
I've merged a PR to fix this behaviour, I appreciate the report!  I'll try to put out a release tonight

**Closed** 2024-12-03 07:57 UTC
Labels: bug
