### ISSUE TITLE
Application Not Updated for iOS 18 Beta

### ISSUE THREAD

**Issue by MonopolyMan27** [LiamMorrow/LiftLog#225] opened 2024-07-25 04:49 UTC
App launches to blank screen on iPhone 15 running iOS 18 Beta.
![blank_app_liftlog](https://github.com/user-attachments/assets/b9a10573-acab-4f47-a35e-4d1501d94d4f)

**Comment by LiamMorrow** [comment] 2024-07-25 23:15
Thanks for the report! Hmm, I'll have to see what I can do, I don't run any of the Betas, but I'll see if it happens in the simulator

**Comment by LiamMorrow** [comment] 2024-07-25 23:23
Looks like it could be related to this:
https://github.com/dotnet/maui/issues/23390#issue-2385115496

**Comment by LiamMorrow** [comment] 2024-07-26 00:01
Thanks so much for the report! I've confirmed the behaviour in the simulator on ios 18, and the fix seems to work.  I'm pushing out an update this morning, so it should be fixed next update :)

**Closed by LiamMorrow** 2024-07-26 00:01 UTC
